"""empty message

Revision ID: 59b185341dcc
Revises: 
Create Date: 2020-05-12 18:45:08.467931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b185341dcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio', sa.Column('img', sa.String(length=10), nullable=True))
    op.add_column('radio', sa.Column('site', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio', 'site')
    op.drop_column('radio', 'img')
    # ### end Alembic commands ###
